# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in ipgeobase.gemspec
gemspec

gem 'rake', '~> 13.0'

gem 'rubocop', '~> 1.21'

gem 'addressable'
gem 'nokogiri-happymapper', require: 'happymapper'

# gem "minitest", "~> 5.0"
gem 'minitest-power_assert'

group :test do
  gem 'webmock'
end

gem 'simplecov', require: false, group: :test
