# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'puma'
gem 'rails', '~> 7.0'
gem 'sqlite3'
# gem 'sprockets', '< 4'
gem 'jbuilder'
gem 'turbolinks'
gem 'webpacker'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'bootsnap', '>= 1.4.4', require: false

  gem 'listen', '~> 3.3'
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'spring'
  gem 'web-console', '>= 4.1.0'
end

group :test do
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end

gem 'rexml', '~> 3.2', '>= 3.2.4'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
