# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'jbuilder'
gem 'puma'
gem 'rails', '~> 7.0'
gem 'sqlite3'
gem 'turbolinks'
gem 'webpacker'

gem 'slim-rails'
# BEGIN
gem 'simple_form'
# END
gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'spring'
  gem 'web-console', '>= 4.1.0'
end

group :test do
  gem 'faker'
  gem 'minitest-power_assert'
end

gem 'rexml', '~> 3.2', '>= 3.2.4'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
